<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
</head>
<body>



<div class="container" style="margin-left: 40px; margin-top: 80px;">

	<div class="notes">
		<h3>Security Notes</h3><br>
		<p>1. CSRF token -> for form security use csrf token 
	The CSRF token is added to the form as a hidden input only when the form_open() function is used.
	
	Cross-Site Request Forgery (CSRF) is an attack that forces an end user to execute unwanted actions on a web application in which they're currently authenticated. CSRF attacks specifically target state-changing requests, not theft of data, since the attacker has no way to see the response to the forged request.

	You can prevent this attack by enabling it in the application/config/config.php
	$config['csrf_protection'] = TRUE;	

	now inspect element the form you will see a hidden field is generated by server it is csrf field</p> <br>
	<hr>

	<p>2. xss_clean -> XSS means Cross-site scripting, which is a type of security vulnerability found in web application. The XSS technique commonly used to trigger Javascript or other types of malicious code that attempt to hijack runnable code.
Usage of xss_clean(), we can stop the data and filter up, if any disallowed data is encountered it is rendered by xss_clean function and safe convert into the character entities.
Without the using of xss_clean(), encountered data via cookies and post, get method directly applied to the code, which is harmful. <br>
$this->load->library("security"); I have load this class in config file and will be access everywhere.
Executing xss_clean function using security class.
$data = $this->security->xss_clean($data);
$config['global_xss_filtering'] = FALSE;  to $config['global_xss_filtering'] = TRUE;
<hr>
security ta agge version glo te library chilo but akhn helper kre diyeche .... to autoload e helper e secrity add krechi
</p><br>

	</div>

	<?php echo form_open('LoginController/index'); ?>
		Email :- <input type="text" name="email"><br>	
		Password :- <input type="password" name="password"><br>		
		<input type="submit" name="submit" value="submit">
	<?php echo form_close(); ?>
</div>

</body>
</html>